version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ssu-it-locker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-i6ml612z96ny"
s3_prefix = "ssu-it-locker"
region = "ap-northeast-2"
profile = "globalmedia"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "TableName=\"LockerTable\" AwsSamLocal=\"\" AdminId=\"20211561\""
